chatwoot/chatwoot-mobile-app

- src/app.js
- src/i18n/en.json
> Add confirm modal on hardware back button

- package.json
- src/components/NoNetworkBar.js
- src/router.js
- yarn.lock
> Feature: add no network bar

- package.json
- src/reducer/auth.js
- src/reducer/tests/auth.spec.js
-  Jest config is setup to look for files inside `src` folder with files that end with `.spec.js` or `.test.js`
- (Opinion) The test file for each unit would be in `tests` folder and this `tests` folder would be in the same directory.
> Setting up jest to test reducers

- src/actions/inbox.js
- src/helpers/APIHelper.js
> Bug: Application redirect to login page if token is expired

- src/screens/ConversationList/ConversationList.style.js
> Fix: Conversation tab header font responsiveness

- .circleci/config.yml
> Circle CI Init

- src/constants/url.js
- src/helpers/index.js
- src/screens/ConversationList/ConversationList.js
- src/screens/ConversationList/ConversationList.style.js
- src/screens/LoginScreen/LoginScreen.js
- src/screens/Settings/SettingsScreen.js
> Fix: Add the external URL open features 

- src/components/ConversationItem.js
> Fix: Random color for each conversation item avatar 

- src/components/ConversationItem.js
> Bug: Fix the content length issue in conversation item

- src/screens/Settings/SettingsScreen.js
> Bug: Fix the issue with rendering agent avatar

- src/constants/url.js
- src/screens/LoginScreen/LoginScreen.js
- src/screens/LoginScreen/LoginScreen.style.js
> Fix: The login page responsiveness issue in small screens

- package.json
- src/app.js
- yarn.lock
> Fix: Hide splash screen after mounting the conversation list page

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
> Release: Publish Android/iOS beta version 0.0.14

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/FilterItem.js
- src/screens/LoginScreen/LoginScreen.style.js
> Chore: Add the click option for conversation filter item

- src/actions/auth.js
- src/app.js
- src/i18n/en.json
> Bug: Show success/error message after the login action 

- src/actions/inbox.js
- src/components/FilterItem.js
- src/constants/index.js
- src/screens/ConversationFilter/ConversationFilter.js
Fixes #91 
**Preview**
**iOS**
**Android**
> Feature: Add icons for conversation filter items

- ios/Podfile.lock
- src/actions/conversation.js
- src/actions/inbox.js
- src/constants/url.js
- src/helpers/APIHelper.js
- src/helpers/AuthHelper.js
- yarn.lock
> Feature: Update all the API end points based on account id 

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/components/ConversationItem.js
- src/components/ConversationItemLoader.js
- src/components/SettingsItem.js
- src/components/TabBar.js
- src/components/TextInputField.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ConversationFilter/ConversationFilter.style.js
- src/screens/ForgotPassword/ForgotPassword.style.js
- src/screens/LoginScreen/LoginScreen.js
- src/screens/LoginScreen/LoginScreen.style.js
- src/screens/Settings/SettingsScreen.js
- src/screens/Settings/SettingsScreen.style.js
- src/theme.js
> Feature : Theme customisation

- package.json
- yarn.lock
> Security: Upgrade eslint to 6.8.0

- README.md
- src/components/ChatMessage.js
- src/components/ConversationItem.js
- src/components/ImageLoader.js
- src/helpers/formHelper.js
- src/i18n/en.json
- src/router.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ChatScreen/ChatScreen.style.js
- src/screens/ChatScreen/ImageScreen.js
- src/screens/ConversationFilter/ConversationFilter.js
- src/screens/ConversationList/ConversationList.js
- src/screens/ConversationList/ConversationList.style.js
- src/screens/Settings/SettingsScreen.js
> Feature: Add image type message

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/ConversationItem.js
- src/components/ImageLoader.js
- src/components/LoaderButton.js
- src/components/UserAvatar.js
- src/screens/Settings/SettingsScreen.js
> Feature: Add image loader

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/screens/ChatScreen/ImageScreen.js
- yarn.lock
> Feature: Add image zooming

- src/components/ChatMessage.js
- src/components/ConversationItem.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ConversationList/ConversationList.style.js
- src/store.js
> Feature: Show sender details on tooltip

- ios/Podfile.lock
- src/components/ChatAttachmentItem.js
- src/components/ChatMessage.js
- src/components/ChatMessageItem.js
- src/components/ConversationAttachmentItem.js
- src/components/ConversationItem.js
- src/i18n/en.json
- src/screens/ChatScreen/ChatScreen.js
> Feature: Add rich message types (image and file)

- src/components/ConversationItem.js
- src/helpers/index.js
- src/screens/ConversationList/ConversationList.js
> Feature: Add inbox label in conversation item

- android/app/proguard-rules.pro
- package.json
- yarn.lock
> Fix: Crashing the latest android beta release 

- android/app/build.gradle
- android/app/proguard-rules.pro
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/RootNavigation.js
- src/actions/auth.js
- src/actions/settings.js
- src/components/ChatMessageItem.js
- src/components/ConversationItem.js
- src/constants/url.js
- src/helpers/index.js
- src/i18n/en.json
- src/reducer/settings.js
- src/router.js
- src/screens/ConversationList/ConversationList.js
- src/screens/LoginScreen/LoginScreen.js
- src/screens/Settings/SettingsScreen.js
> Feature: Add the support for private type messages

- src/components/ChatAttachmentItem.js
- src/components/ChatMessage.js
- src/reducer/index.js
> Fix: Render multiple file attachement issue

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/components/ChatMessageDate.js
- src/components/ChatMessageItem.js
- src/components/ConversationItem.js
- src/helpers/DateHelper.js
- src/helpers/index.js
- src/i18n/en.json
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ChatScreen/ChatScreen.style.js
- src/screens/ConversationList/ConversationList.js
- src/theme.js
- yarn.lock
> Feature: Implement  group conversations by date

- src/components/ScrollToBottomButton.js
- src/screens/ChatScreen/ChatScreen.js
> Feature: Add scroll to bottom button in chat screen

- src/actions/conversation.js
- src/helpers/ActionCable.js
> Fix: Conversations list update issue on conversation reopen

- src/actions/conversation.js
> Bug: Fix the unread count update issue in conversation

- .gitignore
- android/app/build.gradle
- index.js
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/actions/auth.js
- yarn.lock
> Feature: Setup sentry for error reporting

- .gitignore
- android/app/build.gradle
- android/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Chatwoot/AppDelegate.m
- ios/Chatwoot/Chatwoot.entitlements
- ios/Podfile.lock
- package.json
- src/actions/settings.js
- src/screens/ConversationList/ConversationList.js
- yarn.lock
> Feature:  Setup firebase

- ios/Podfile.lock
- package.json
- src/app.js
- src/helpers/ErrorHelper.js
- src/i18n/en.json
- yarn.lock
> Feature: Add global error handler 

- src/screens/ChatScreen/ImageScreen.js
> Bug: Fix the back button issue in attachment preview  

- src/actions/auth.js
- src/components/ConversationItem.js
- src/components/NoNetworkBar.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ConversationList/ConversationList.js
> Fix: Language switch issue

- android/app/build.gradle
- package.json
> Performance: Enable herms engine in android

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/components/UserAvatar.js
- src/helpers/index.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ChatScreen/ChatScreen.style.js
- yarn.lock
> Feature: Add linear gradient user thumbnail

- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/ChatAttachmentItem.js
- src/components/ChatMessageItem.js
- src/components/UserAvatar.js
- src/i18n/en.json
- src/router.js
- src/screens/ConfigureURLScreen/ConfigureURLScreen.js
- yarn.lock
> Bug: Support hyperlink in message

- src/actions/auth.js
- src/i18n/en.json
> Fix: App crashing on no accounts case

- src/actions/conversation.js
- src/components/ConversationAttachmentItem.js
- src/components/ConversationContentItem.js
- src/components/ConversationItem.js
- src/components/ImageLoader.js
- src/components/NotificationItem.js
- src/components/Text.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ConversationDetails/ConversationDetailsScreen.js
- Style fixes in the chat screen
- Fix prop type warnings
- Split conversation content item to a separate component
- Fix the channel issue in channel screen
> Fix: design issues in chat screen

- src/actions/notification.js
> Fix: notifications get cleared on infinite scroll

- src/components/TabBar.js
> Feature: Add notification unread count in footer bar

- src/components/TabBar.js
> Bug: Notification count update issue

- src/screens/ConversationList/ConversationList.js
> Feature: Pull to refresh in conversation list

- src/actions/conversation.js
- src/helpers/index.js
- src/screens/ConversationList/ConversationList.js
> Fix: Conversation is not adding to the correct list 

- src/actions/auth.js
- src/components/ChatMessageItem.js
- src/screens/ConversationList/ConversationList.js
> fix: conversation list infinite scroll

- android/app/build.gradle
- android/fastlane/README.md
- package.json
- src/screens/ChatScreen/ChatScreen.js
> Fix: conversation menu display issue for lengthy user name

- src/actions/auth.js
- src/actions/conversation.js
- src/constants/index.js
- src/helpers/index.js
- src/i18n/en.json
- src/screens/ConversationFilter/ConversationFilter.js
- Fix the crash issue on status action cable event
- Added bot filter
> Chore: Fixes and improvments 

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/components/ChatMessageItem.js
- src/components/ConversationItem.js
- src/helpers/formHelper.js
- src/screens/ChatScreen/ChatScreen.style.js
- src/screens/LoginScreen/LoginScreen.js
- src/screens/Settings/SettingsScreen.js
- src/theme.js
- yarn.lock
> Chore: fixes and improvements

- src/actions/notification.js
- src/helpers/PushHelper.js
- src/screens/ConfigureURLScreen/ConfigureURLScreen.js
> Feature: Update badge count after receiving the notification

- README.md
> Chore: Update mobile applications production URLs

- src/screens/LoginScreen/LoginScreen.js
> fix: disable auto capitalize in login screen

- package.json
- src/actions/conversation.js
- src/components/ConversationActionItem.js
- src/i18n/en.json
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ConversationAction/ConversationAction.js
- yarn.lock
> Enhancement: show conversation actions in action view

- src/components/NotificationActionItem.js
- src/screens/Notification/NotificationScreen.js
> Enhancement: show notification actions in action view 

- ios/Podfile.lock
- package.json
- src/components/ChatMessageActionItem.js
- src/components/ChatMessageItem.js
- src/screens/ChatScreen/ChatScreen.js
- yarn.lock
> feat: allow copying conversation message

- src/screens/ChatScreen/ImageScreen.js
> fix: close button on image modal

- src/screens/Notification/NotificationScreen.js
> feat: scroll to refresh in notification page

- src/constants/index.js
> chore: add missing inbox icons

- CUSTOM_RELEASE_GUIDE.md
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Chatwoot/AppDelegate.m
- ios/Chatwoot/Chatwoot.entitlements
- ios/Chatwoot/Info.plist
- package.json
- src/router.js
> feature: universal linking in iOS

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/ChatMessageItem.js
- src/components/ConversationContentItem.js
- yarn.lock
> feature: render user mentions in private note

- src/screens/ChatScreen/components/CannedResponses.js
- src/screens/ChatScreen/components/ReplyBox.js
> enhancement: canned responses view

- ios/Podfile.lock
- package.json
- src/screens/ChatScreen/components/Attachment.js
- yarn.lock
> Feature: allow support for sending documents

- src/i18n/en.json
- src/router.js
- src/screens/Language/LanguageScreen.js
- src/screens/LoginScreen/LoginScreen.js
> feature: Allow changing language in logged out screen

- .env.example
- CONTRIBUTING.md
- android/app/build.gradle
- index.js
- ios/Podfile.lock
- package.json
- yarn.lock
> chore: add config for exposing environment variables

- src/actions/conversation.js
- src/components/ConversationActionItem.js
- src/i18n/en.json
- src/screens/ChatScreen/components/ChatHeader.js
- src/screens/ConversationAction/ConversationAction.js
- src/screens/LoginScreen/LoginScreen.js
> feature: unassign agent from conversation

- src/screens/ChatScreen/components/ChatAttachmentItem.js
> chore: support audio type messages

- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- package.json
- yarn.lock
> Chore: update sentry version

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/ChatAttachmentItem.js
> Fix: App crashing while loading media messages without content

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- yarn.lock
> Chore: Upgrade rn-exception handler

- babel.config.js
- src/screens/ChatScreen/components/ChatHeader.js
- src/screens/ChatScreen/components/ChatMessageItem.js
> Chore: Private message UI fixes

- README.md
- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/ConversationContentItem.js
- src/helpers/PushHelper.js
- src/screens/ChatScreen/components/ChatHeader.js
> fix: Application crashing when open by clicking on notification 

- src/screens/AgentScreen/AgentScreen.js
> fix: Application crashes when try to assignee a new agent

- package.json
- src/screens/ChatScreen/components/MentionUser.js
- src/screens/ChatScreen/components/ReplyBox.js
- src/screens/ConversationDetails/ConversationDetailsScreen.js
- yarn.lock
Fixes #266 
**Preview**
https://user-images.githubusercontent.com/12408980/115666091-fd49e680-a2f8-11eb-8194-dfa9b3b5bdab.mov
> feature: Mention agents in private note reply box

- src/actions/inbox.js
> chore: Add admins in conversation assignee list

- src/constants/url.js
- src/screens/ChatScreen/components/ChatHeader.js
> fix: Flickering user avatar in conversation header

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/helpers/Analytics.js
- src/screens/AgentScreen/AgentScreen.js
- src/screens/ConversationFilter/ConversationFilter.js
> chore: Add scroll in assign agent screen

- src/components/ConversationContentItem.js
> chore: Format mentioned user name If user name contains the white space

- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
> chore: Show messages when replying to conversation notifications 

- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- yarn.lock
> chore: Add development support for apple m1 devices

- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- src/screens/Settings/SettingsScreen.js
- src/screens/Settings/SettingsScreen.style.js
> fix: Logo overflow in settings screen

- src/screens/ConversationDetails/ConversationDetailsScreen.js
> fix: Invariant violation of text in chat header

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/ConversationItem.js
> fix: App crashing when contact name is empty

- ios/Chatwoot.xcodeproj/project.pbxproj
- src/screens/AgentScreen/AgentScreen.style.js
> fix: Show button in conversation assignment screen

- README.md
> doc: Add beta testing details

- src/constants/index.js
- src/helpers/index.js
- src/i18n/en.json
- src/screens/ConversationFilter/ConversationFilter.js
- src/screens/ConversationFilter/ConversationFilter.style.js
- src/screens/NotificationPreference/NotificationPreference.js
> chore: Add pending and resolved status in conversation filter screen

- src/screens/ConversationList/components/ConversationContentItem.js
- src/screens/ConversationList/components/ConversationItem.js
> enhancement: Change private note icon in conversation list

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/notification.js
- src/helpers/PushHelper.js
- src/screens/ConversationList/ConversationList.js
> fix: FCM refresh token update

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/helpers/PushHelper.js
> fix: Reset badge count if all notifications are read

- src/constants/index.js
- src/screens/ChatScreen/components/ChatMessageDate.js
> chore: Adds missing inbox icons

- src/helpers/UrlHelper.js
- src/i18n/en.json
- src/screens/ConversationAction/ConversationAction.js
Fixes #334 
1. Open a conversation and select the three dots icon from the top right corner.
2. Now you can see share button.
3. Select the share button now you will see the native share dialog.
> feat: Adds the ability to share the conversation

- src/screens/Availability/Availability.js
fix: 'Availability types' were not translated
> fix: Availability types translation

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ChatScreen/components/Attachment.js
- src/screens/ChatScreen/components/ReplyBox.js
Allowing the ability to upload more common file types like zip, Docx etc
> chore: Allow more files types in uploads

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/helpers/index.js
Fixed the conversations update issue under unassigned tab
> fix:  Conversations update issue under unassigned tab

- android/app/proguard-rules.pro
> fix: Support us option in settings menu

- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Chatwoot/Info.plist
- package.json
- src/app.js
Fixes #440 
- Disable dark mode
- Render iPad apps properly
> fix: Disable dark mode, render iPad apps properly

- src/screens/Account/AccountScreen.js
- src/screens/ConversationList/components/ConversationItem.js
> fix: Add scroll view in account screen

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/screens/ChatScreen/components/ChatAttachmentItem.js
> fix: Force logout if the token is expired

- android/app/build.gradle
- index.js
- package.json
- react-native-setup-ios.sh
- src/app.js
- yarn.lock
Fixes https://github.com/chatwoot/product/issues/428
> chore: Move sentry to new account

- README.md
The documentation didn't show the correct badge for the license type. Updated the documentation to show the same.
Fixes #515 
> Fixes license badge

- src/screens/ChatScreen/components/Attachment.js
- src/screens/ChatScreen/components/ChatAttachmentItem.js
- src/screens/ChatScreen/components/ChatMessageItem.js
- src/screens/ChatScreen/components/ReplyBox.js
- src/theme.js
This PR adds the ability to increase the height of the input field.
Fixes #508
1. Open a conversation.
2. Now you can see an expand button on the bottom left side.
**Screencast**
https://user-images.githubusercontent.com/64252451/168733170-6a950f80-7215-487c-940b-bdd2d0fe943f.mov
> feat: Adds ability to expanded reply box

- src/components/ConversationDetailsItem.js
- src/components/HeaderBar.js
- src/helpers/UrlHelper.js
- src/i18n/en.json
- src/screens/ConversationDetails/ConversationDetailsScreen.js
- src/screens/ConversationDetails/ConversationDetailsScreen.style.js
- src/screens/ConversationDetails/components/ContactDetails.js
- src/screens/ConversationDetails/components/SocialProfileIcons.js
This PR includes,
1. Missing sender details.
2. Improved UI/UX.
Fixes https://github.com/chatwoot/chatwoot-mobile-app/issues/543
**Screenshot**
> enhancement: Missing contact details

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/ChatHeader.js
- src/screens/ChatScreen/components/ChatMessageItem.js
- src/screens/ChatScreen/components/InboxName.js
- src/screens/ChatScreen/components/UserTypingStatus.js
1. Adds fix for push notifications related issues.
2. Fixes overflow issue related to typing name indicator
> fix: Notification related issue and text overflow

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/conversation.js
- src/components/Text.js
- src/screens/ChatScreen/components/ChatMessageItem.js
> chore: Sentry fixes

- .eslintignore
- android/app/build.gradle
- index.js
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/components/StoryBookView.js
- src/components/Text/Text.js
- src/components/Text/Text.stories.js
- src/router.js
- storybook/addons.js
- storybook/index.js
- storybook/rn-addons.js
- storybook/storyLoader.js
- yarn.lock
Fixes #10 
- Added `@storybook/react-native`.
- Added `@storybook/react-native-server`.
- Added & configured `react-native-storybook-loader`.
- Added stories for `Text` component.
**How to run storybook?**
Install all the packages
```
yarn
```
Run the storybook server.
```
yarn prestorybook  && yarn run storybook
```
Start the package.
```
yarn start
```
Run the app on device.
```
yarn android or yarn ios
```
_Note: Comment the line number 11 in `index.js` to see the storybook in the mobile app._
**Screenshots**
> chore: Add storybook

- .vscode/settings.json
- index.js
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- src/components/Header/Header.js
- src/components/Header/Header.spec.js
- src/components/Header/Header.stories.js
- src/components/Icon/Icon.stories.js
- src/components/Pressable/Pressable.js
- src/components/Pressable/Pressable.spec.js
- src/components/Pressable/Pressable.stories.js
- src/components/StoryBookView.js
- storybook/storyLoader.js
- yarn.lock
Fixes https://github.com/chatwoot/product/issues/608
https://user-images.githubusercontent.com/64252451/199504873-5ab5c9de-8197-405b-9878-fa287bff4992.mp4
> feat: Header component

- .gitignore
- android/app/build.gradle
- index.js
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/helpers/UrlHelper.js
- src/screens/ConversationDetails/components/ContactDetails.js
> fix: Phone number call action in contact details

- src/components/Empty/Empty.js
- src/components/Empty/Empty.spec.js
- src/components/Empty/Empty.stories.js
- src/screens/Conversation/components/ConversationItem/ConversationEmptyMessage.js
- storybook/storyLoader.js
Fixes https://github.com/chatwoot/product/issues/610
https://user-images.githubusercontent.com/64252451/200328935-fc5a7a35-ff1a-4bbe-96d6-94d2617dedf0.mp4
> feat: Conversation empty component

- src/components/FilterButton/FilterButton.js
- src/components/FilterButton/FilterButton.spec.js
- src/components/FilterButton/FilterButton.stories.js
- storybook/storyLoader.js
https://user-images.githubusercontent.com/64252451/200287474-3aa354f6-d49a-4c07-8a71-79e26037b9dd.mp4
> feat: Filter bottom sheet toggle button

- src/components/BottomSheetHeader/BottomSheetHeader.js
- src/components/BottomSheetHeader/BottomSheetHeader.stories.js
- src/components/Icon/Icon.stories.js
- src/components/InboxName/InboxName.js
- src/components/InboxName/InboxName.stories.js
- src/components/Pressable/Pressable.stories.js
- src/constants/index.js
- src/screens/Conversation/components/ConversationFilter/ConversationFilter.js
- src/screens/Conversation/components/ConversationFilter/ConversationFilter.stories.js
- storybook/storyLoader.js
Fixes https://github.com/chatwoot/product/issues/616 https://github.com/chatwoot/product/issues/614
https://user-images.githubusercontent.com/64252451/201016087-74de6a44-7590-4d05-81b5-574e8bac9033.mp4
> feat: Conversation assignee and status filter component

- src/components/index.js
- src/screens/Conversation/components/ConversationFilter/ConversationFilter.js
- src/screens/Conversation/components/ConversationFilter/ConversationFilter.stories.js
- src/screens/Conversation/components/ConversationFilter/ConversationInboxFilter.js
- src/screens/Conversation/components/ConversationFilter/ConversationInboxFilter.stories.js
- storybook/storyLoader.js
Fixes https://github.com/chatwoot/product/issues/615
https://user-images.githubusercontent.com/64252451/201291420-c7b1332b-c9b3-405a-9596-0407a2e40de1.mp4
> feat: Conversation inbox filter component

- android/app/proguard-rules.pro
- babel.config.js
- ios/Podfile.lock
- package.json
- src/app.js
- src/components/FilterButton/ClearFilterButton.js
- src/components/FilterButton/FilterButton.js
- src/components/index.js
- src/constants/index.js
- src/reducer/conversationSlice.js
- src/router.js
- src/screens/Conversation/ConversationScreen.js
- src/screens/Conversation/ConversationScreen.style.js
- src/screens/Conversation/components/ConversationEmptyItem/ConversationEmptyItem.style.js
- src/screens/Conversation/components/ConversationEmptyList/ConversationEmptyList.js
- src/screens/Conversation/components/ConversationFilter/ConversationFilter.js
- src/screens/Conversation/components/ConversationFilter/ConversationInboxFilter.js
- src/screens/Conversation/components/ConversationItem/ConversationContent.js
- src/screens/Conversation/components/ConversationItem/ConversationItem.js
- src/screens/Conversation/components/index.js
- src/theme.v2.js
- yarn.lock
Fixes https://github.com/chatwoot/product/issues/617, https://github.com/chatwoot/product/issues/619, https://github.com/chatwoot/product/issues/618
> feat: Conversation filters

- src/app.js
- src/components/UserAvatar/UserAvatar.js
- src/screens/Conversation/ConversationScreen.js
> fix: Bottom sheet memory leak issue

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/actions/auth.js
- src/constants/index.js
- src/helpers/DeepLinking.js
- src/helpers/PushHelper.js
- src/helpers/conversationHelpers.js
- src/helpers/specs/conversationHelpers.spec.js
- src/reducer/conversationSlice.action.js
- src/reducer/conversationSlice.js
- src/router.js
- src/screens/Account/AccountScreen.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/ChatScreen/components/ChatMessageItem.js
- src/screens/ChatScreen/components/ReplyBox.js
- yarn.lock
> feat: Add pending message

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/ChatHeader.js
- src/screens/Conversation/ConversationScreen.js
- Fixed count update when the app opens from a closed state. 
- Replaced `UserAvatar` in the chat screen header.
> fix: Notification badge count 

- ios/Podfile.lock
- package.json
- src/reducer/index.js
- src/screens/Notification/NotificationScreen.js
- src/store.js
- yarn.lock
> chore: Upgrade redux

- src/constants/index.js
- src/i18n/id.json
- src/i18n/index.js
Add *Bahasa Indonesia* language support for Indonesian users arround the globe.
- No issue fixed
Yes, all of code was work as main branch with no modification, i'm just adding new lang support
> Add indonesian language support

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/helpers/AnalyticsHelper.js
> fix: Account validation in analytics

- src/i18n/en.json
- src/screens/ChatScreen/components/ChatHeader.js
- src/screens/ConversationAction/ConversationAction.js
> feat: Self assign conversation

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/ChatMessageItem.js
- src/screens/ChatScreen/components/Email.js
- Fixed infinite scroll issue in email content.
- Disabled block quote rendering.
Fixes #https://github.com/chatwoot/product/issues/802
> fix: Message rendering

- src/helpers/ActionCable.js
- src/reducer/index.js
- src/reducer/specs/teamSlice.spec.js
- src/reducer/teamSlice.js
- src/screens/ChatScreen/components/ReplyBox.js
- src/screens/ConversationAction/ConversationAction.js
- src/screens/TeamScreen/TeamScreen.js
- Added a new slice for team.
- Added the specs.
> feat: Create a separate state for teams

- src/screens/ChatScreen/components/ChatMessageItem.js
Fixes https://github.com/chatwoot/product/issues/811
> fix: Message list icon color for incoming message

- src/reducer/index.js
- src/reducer/notificationSlice.js
- src/reducer/specs/notificationSlice.spec.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/Conversation/ConversationScreen.js
- src/screens/Notification/NotificationScreen.js
- Added a new slice for notification.
- Added the specs.
> feat: Add notification state

- src/components/UserAvatar/UserAvatar.js
- src/screens/Conversation/components/ConversationItem/CardLabels.js
- src/screens/Conversation/components/ConversationItem/ConversationItem.js
- src/theme.v2.js
- Thumbnail font weight and color.
- Handle Assignee name overflow
- Card label spacing
> chore: Chat list minor improvements

- index.js
- ios/Podfile.lock
- package.json
- src/screens/Conversation/ConversationScreen.js
- yarn.lock
> chore: Update `sentry` to the latest version

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/Modal/ModalView.js
- src/i18n/en.json
- src/screens/ChatScreen/components/ReplyBox.js
- yarn.lock
Fixes https://linear.app/chatwoot/issue/CW-368/replace-variables-while-selecting-canned-response-for-mobile-app
**Screenrecording**
https://user-images.githubusercontent.com/64252451/235125741-2b6f2b2b-4dca-459f-bca4-ea713ac11bce.mp4
> feat: Replace variables while selecting canned response

- android/app/build.gradle
- android/app/src/main/assets/modules.json
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/constants/index.js
- src/i18n/en.json
- src/reducer/conversationSlice.action.js
- src/reducer/conversationSlice.js
- src/reducer/specs/conversationSlice.reducer.spec.js
- src/screens/Conversation/ConversationScreen.js
- src/screens/Conversation/components/ConversationList/ConversationList.js
Fixes https://linear.app/chatwoot/issue/CW-1809/conversation-order-by-filter
> feat: Add sort filter for conversations

- src/screens/LoginScreen/LoginScreen.js
This pull request resolves the issue of the login button being unclickable when the keyboard is inactive.
> fix: First time login button click

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/Conversation/components/ConversationItem/ConversationItem.js
- Handle the message if it's empty. Causes app crash.
> build: Version 1.10.1

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/constants/index.js
- src/screens/ChatScreen/ChatScreen.js
- src/screens/Conversation/ConversationScreen.js
- src/screens/Notification/NotificationScreen.js
Fixes https://linear.app/chatwoot/issue/CW-2250/refetching-logic-is-broken
> feat: Refresh conversations when the app open from inactive state

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/helpers/index.js
This pull request adds a fix for messages being out of order in some cases.
> fix: Sort messages by created date

- android/app/build.gradle
- android/app/proguard-rules.pro
- android/app/src/main/assets/modules.json
- package.json
> chore: nable herms in android

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/Email.js
> fix: Auto height issues in email messages

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/reducer/authSlice.js
> fix: Non-serializable value update in auth slice

- ios/Podfile.lock
- package.json
- yarn.lock
- Upgraded react native web view to the latest version.
> chore: Bump `react-native-webview`

- src/screens/ChatScreen/components/ChatMessageItem.js
This PR includes fix for email conversation width.
Fixes https://linear.app/chatwoot/issue/CW-2502/email-message-full-body-width
https://linear.app/chatwoot/issue/CW-2502/email-message-full-body-width
> fix: Email message full body width.

- src/screens/ChatScreen/components/ConversationLabels.js
- src/screens/Conversation/components/ConversationItem/CardLabels.js
- src/screens/Conversation/components/ConversationItem/ConversationLabels.js
- src/screens/ConversationDetails/components/LabelView.js
Fixes https://linear.app/chatwoot/issue/CW-2475/app-is-crashing-when-the-label-is-added-first-time
> fix: App is crashing when the label is added first time

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/reducer/conversationSlice.selector.js
- src/screens/ChatScreen/components/Email.js
- src/screens/ChatScreen/components/MessageDeliveryStatus.js
- src/screens/ChatScreen/components/MessageList/MessageList.js
- src/screens/ChatScreen/components/MessageList/MessageList.style.js
- src/screens/ChatScreen/components/MessageList/messages.js
> feat: Replace SectionList with Flashlist in chat screen

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/helpers/PushHelper.js
- src/helpers/specs/pushHelper.spec.js
- src/router.js
> feat: FCM HTTP v1 changes

- src/i18n/pt_BR.json
Enhance correct translations in pt_BR.json
> chore: New translations pt_BR.json (Portuguese, Brazilian)

- android/app/build.gradle
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/screens/ChatScreen/components/ChatAttachmentItem.js
Fixes https://linear.app/chatwoot/issue/CW-3550/typeerror-cannot-read-property-image-type-of-undefined
>  fix: Check content attributes exist or not in chat attachment component

- ReactotronConfig.js
- android/app/build.gradle
- index.js
- ios/Chatwoot.xcodeproj/project.pbxproj
- package.json
- src/components/TabBar.js
- src/constants/permissions.js
- src/helpers/permissionHelper.js
- src/reducer/authSlice.js
- src/screens/Conversation/ConversationScreen.js
- src/screens/Settings/SettingsScreen.js
- src/screens/Settings/components/AccountsSelector.js
- yarn.lock
Custom roles changes related https://github.com/chatwoot/chatwoot/pull/9865
> feat: Custom roles

- src/types/Account.ts
- src/types/Agent.ts
- src/types/AgentBot.ts
- src/types/Contact.ts
- src/types/Conversation.ts
- src/types/Message.ts
- src/types/Team.ts
- src/types/User.ts
- src/types/common/AvailabilityStatus.ts
- src/types/common/Channel.ts
- src/types/common/ConversationPriority.ts
- src/types/common/ConversationStatus.ts
- src/types/common/UnixTimestamp.ts
- src/types/common/UserRole.ts
- src/types/common/index.ts
- src/types/index.ts
We have added support for TypeScript. This pull request will introduce types for use throughout the project.
> feat: Add TS types

- src/store/contact/contactActions.ts
- src/store/contact/contactSelectors.ts
- src/store/contact/contactService.ts
- src/store/contact/contactSlice.ts
- src/store/contact/contactTypes.ts
- src/store/contact/specs/contactActions.spec.ts
- src/store/contact/specs/contactMockData.ts
- src/store/contact/specs/contactSelectors.spec.ts
- src/store/contact/specs/contactService.spec.ts
- src/store/contact/specs/contactSlice.spec.ts
> feat: Add contact store

- __mocks__/@sentry/react-native.js
- __mocks__/reactotron-react-native.js
- __mocks__/reactotron-redux.js
- package.json
- pnpm-lock.yaml
- src/store/inbox/inboxActions.ts
- src/store/inbox/inboxSelectors.ts
- src/store/inbox/inboxService.ts
- src/store/inbox/inboxSlice.ts
- src/store/inbox/inboxTypes.ts
- src/store/inbox/specs/inboxActions.spec.ts
- src/store/inbox/specs/inboxMockData.ts
- src/store/inbox/specs/inboxSelectors.spec.ts
- src/store/inbox/specs/inboxServices.spec.ts
- src/store/inbox/specs/inboxSlice.spec.ts
- src/utils/camelCase.ts
- src/utils/camelCaseKeys.ts
- src/utils/index.ts
> feat: Inbox store

- .storybook/preview.tsx
- src/components-next/common/avatar/AvatarStatus.tsx
- src/components-next/common/bottomsheet/BottomSheet.stories.tsx
- src/components-next/common/icon/Icon.stories.tsx
- Added Icon component stories.
- Add Bottom sheet component stories (Using Language List).
> chore: Add missing component stories

- .storybook/preview.tsx
- src/components-next/common/avatar/AvatarStatus.tsx
- src/components-next/common/bottomsheet/BottomSheet.stories.tsx
- src/components-next/common/icon/Icon.stories.tsx
- src/components-next/common/index.ts
- src/components-next/common/search/SearchBar.stories.tsx
- src/components-next/common/search/SearchBar.tsx
- src/components-next/common/search/index.ts
- src/components-next/common/spinner/Spinner.tsx
- src/components-next/common/spinner/index.ts
- src/utils/index.ts
- src/utils/withAnchorPoint.ts
> feat: Add `SearchBar` component

- .storybook/preview.tsx
- src/components-next/common/avatar/AvatarStatus.tsx
- src/components-next/common/bottomsheet/BottomSheet.stories.tsx
- src/components-next/common/icon/Icon.stories.tsx
- src/components-next/common/index.ts
- src/components-next/common/search/SearchBar.stories.tsx
- src/components-next/common/search/SearchBar.tsx
- src/components-next/common/search/index.ts
- src/components-next/common/spinner/Spinner.tsx
- src/components-next/common/spinner/index.ts
- src/components-next/common/swipeable/Swipeable.stories.tsx
- src/components-next/common/swipeable/Swipeable.tsx
- src/components-next/common/swipeable/index.ts
- src/components-next/native-components/NText.tsx
- src/components-next/native-components/NView.tsx
- src/components-next/native-components/index.ts
- src/utils/index.ts
- src/utils/withAnchorPoint.ts
> feat: Add `swipeable` component

- src/hooks/useHeaderAnimation.ts
- src/navigation/stack/ConversationStack.tsx
- src/screens/conversations/components/conversation-header/ConversationHeaderPresenter.stories.tsx
- src/screens/conversations/components/conversation-header/ConversationHeaderPresenter.tsx
- src/screens/conversations/components/conversation-header/index.ts
> feat: Add conversation header

- app.config.ts
- src/screens/chat-screen/components/message-components/CommandOptionsMenu.tsx
> fix: Permission issues while selecting images in Android.

- .aidigestignore
- src/screens/auth/ConfigURLScreen.tsx
- src/screens/auth/ForgotPassword.tsx
- src/screens/auth/LoginScreen.tsx
- src/screens/chat-screen/components/message-components/MarkdownBubble.tsx
- src/screens/chat-screen/components/reply-box/MessageTextInput.tsx
> fix: Status bar issues in android

- app.config.ts
- package.json
- src/constants/index.ts
- src/screens/chat-screen/components/message-list/MessagesListContainer.tsx
- src/screens/conversations/ConversationScreen.tsx
When users minimize the app, JavaScript code stops executing after some time. When they reopen the app later, there's a risk of missing messages, conversations, or notifications. This PR implements data synchronisation to update conversations and messages when the app resumes from a background state.
> feat: Update conversation/messages when app opens from background state

- app.config.ts
- package.json
- src/screens/chat-screen/components/message-components/CommandOptionsMenu.tsx
This PR fixes the issues with file uploading.
> fix: File upload issues

- app.config.ts
- package.json
- src/i18n/en.json
- src/screens/chat-screen/ChatScreen.tsx
- src/screens/chat-screen/components/macros/MacroContext.tsx
- src/screens/chat-screen/components/macros/MacroDetails.tsx
- src/screens/chat-screen/components/macros/MacroItem.tsx
- src/screens/chat-screen/components/macros/MacroStack.tsx
- src/screens/chat-screen/components/macros/MacrosList.tsx
- src/screens/chat-screen/components/message-components/CommandOptionsMenu.tsx
- src/store/macro/macroActions.ts
- src/store/macro/macroSelectors.ts
- src/store/macro/macroService.ts
- src/store/macro/macroSlice.ts
- src/store/macro/macroTypes.ts
- src/store/macro/specs/macroActions.spec.ts
- src/store/macro/specs/macroMockData.ts
- src/store/macro/specs/macroSelectors.spec.ts
- src/store/macro/specs/macroService.spec.ts
- src/store/macro/specs/macroSlice.spec.ts
- src/store/reducers.ts
- src/types/Macro.ts
- src/types/Team.ts
- src/types/index.ts
- src/utils/camelCaseKeys.ts
- src/utils/macroUtils.ts
- src/utils/specs/macroFixtures.ts
- src/utils/specs/macroUtils.spec.ts
Fixes https://linear.app/chatwoot/issue/CW-3884/add-support-for-macros
> feat: Add macros

- app.config.ts
- package.json
- src/screens/chat-screen/components/reply-box/CannedResponses.tsx
> chore: Fix canned response overlapping issue

- app.config.ts
- package.json
- pnpm-lock.yaml
- src/components-next/common/filters/FilterBar.tsx
- src/components-next/common/filters/FilterButton.tsx
- src/i18n/en.json
- src/screens/chat-screen/components/message-components/ImageBubble.tsx
- src/screens/chat-screen/components/reply-box/MessageTextInput.tsx
- src/screens/conversations/components/conversation-filters/InboxFilters.tsx
- src/screens/conversations/components/conversation-item/stories/ConversationItem.stories.tsx
- src/screens/dashboard/DashboardScreen.tsx
- src/screens/inbox/components/InboxItem.tsx
- src/screens/settings/SettingsScreen.tsx
- src/store/settings/settingsActions.ts
- src/store/settings/settingsService.ts
- src/store/settings/settingsTypes.ts
> chore: Multiple minor fixes and improvements

- app.config.ts
- react-native.config.js
- src/utils/audioConverter.android.ts
- src/utils/audioConverter.ios.ts
- src/utils/pushUtils.ts
> chore: Remove `ffmpeg` and `notifee` from android

- src/screens/chat-screen/components/audio-recorder/AudioRecorder.tsx
> fix: Mic access crash issue
